/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
 var findTheDifference = function(s, t) {
   //build a hast map of s

   //iterate through t
     // check if hash map has letter
     // if undefined or false
      //return letter

      const hashmap = {}
      const hashcomp = {}

      for ( let i = 0; i < t.length; i++ ) {
        if (!hashmap[s[i]] && s[i] !== undefined) {
          hashmap[s[i]] = 0
        }

          hashmap[s[i]]++


        if (!hashcomp[t[i]]) {
          hashcomp[t[i]] = 0
        }
        hashcomp[t[i]]++
      }

      for ( let letter in hashcomp ) {
        if (hashcomp[letter] !== hashmap[letter]) {
          return letter
        }
      }

};

//findTheDifference('aa', 'aaa')

module.exports = findTheDifference

/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.

*/